{
  "comments": [
    {
      "key": {
        "uuid": "3a1e29bb_6ddcc804",
        "filename": "src/main/java/com/googlesource/gerrit/plugins/webhooks/PostTask.java",
        "patchSetId": 3
      },
      "lineNbr": 93,
      "author": {
        "id": 1012987
      },
      "writtenOn": "2018-03-19T19:43:22Z",
      "side": 1,
      "message": "You do not want to retry for any Exception that is not an IOException?\n\nIn the case you faced making you implement this change, would it had recovered on a retry?",
      "range": {
        "startLine": 93,
        "startChar": 11,
        "endLine": 93,
        "endChar": 41
      },
      "revId": "45accb62aa9ba88117ea43ad19fd7d809acc04f6",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    }
  ]
}